name: Build code
on:
  workflow_call:
    inputs:
      artifacts:
        description: Store build as artifact
        default: false
        required: false
        type: boolean
defaults:
  run:
    shell: bash
jobs:
  go-build:
    runs-on: ubuntu-latest
    container: golang:1.23.4-bullseye
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build binaries
        run: go build -mod=vendor -buildvcs=false -trimpath -o build/ -v ./...
      - name: Create archive
        if: ${{ inputs.artifacts }}
        run: tar cvf - build | gzip -1 > build.tar.gz
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ inputs.artifacts }}
        with:
          name: build
          path: build.tar.gz
          retention-days: 1