name: Run checkov
on:
  workflow_call:
defaults:
  run:
    shell: bash
jobs:
  checkov:
    runs-on: ubuntu-latest
    container: golang:1.23.4-bullseye
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@master
        with:
          file: main.tf
          soft_fail: true
