name: CI
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    uses: ./.github/workflows/test.yaml
  lint:
    uses: ./.github/workflows/lint.yaml
  build:
    uses: ./.github/workflows/build.yaml