name: Deploy to DigitalOcean
on:
  workflow_dispatch:
  workflow_call:
defaults:
  run:
    shell: bash
env:
  TF_VAR_digitalocean_token: ${{ secrets.DIGITAL_OCEAN_APP_PLATFORM }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7
      - name: Import existing app (if exists)
        run: |
          terraform import -var "do_token=${{ secrets.DIGITAL_OCEAN_APP_PLATFORM }}" digitalocean_app.zbip-app 3de9aff3-00fe-4574-8045-72435ee8e248
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        # continue-on-error: true
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        # continue-on-error: true
      - name: Deploy to DigitalOcean
        run: terraform apply -auto-approve
      
