name: Deploy
on:
  workflow_dispatch:
jobs:
  test:
    uses: ./.github/workflows/test.yaml
  build:
    uses: ./.github/workflows/build.yaml
    with:
      artifacts: false
  deploy:
    uses: ./.github/workflows/deploy-terraform.yaml
    needs: [build, test]
  track-changes:
    uses: ./.github/workflows/changelog.yaml
    needs: [build, test]
