name: Deploy to DigitalOcean
on:
  workflow_dispatch:
  workflow_call:
defaults:
  run:
    shell: bash
env:
  TF_VAR_digitalocean_token: ${{ secrets.DIGITAL_OCEAN_APP_PLATFORM }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_APP_PLATFORM }}
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        # continue-on-error: true
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Import existing app into Terraform state
        run: |
          terraform import digitalocean_app.zbip-app $(doctl apps list -o json | jq -r ".[] | select(.spec.name == \"zbip-app\") | .id")
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        # continue-on-error: true
      - name: Deploy to DigitalOcean
        run: terraform apply -replace=digitalocean_app.zbip-app -auto-approve
      
