name: Deploy
permissions:
  contents: read
  issues: write
on:
  workflow_dispatch:
jobs:
  test:
    uses: ./.github/workflows/test.yaml
  checkov:
    uses: ./.github/workflows/checkov.yaml
  build:
    uses: ./.github/workflows/build.yaml
    with:
      artifacts: false
  deploy-terraform:
    secrets: inherit
    uses: ./.github/workflows/deploy-terraform.yaml
    needs: [build, test, checkov]
  track-changes:
    secrets: inherit
    uses: ./.github/workflows/track-release.yaml
    needs: [build, test, checkov, deploy-terraform]
