name: Deploy
on:
  workflow_dispatch:
jobs:
  test:
    uses: ./.github/workflows/test.yaml
  build:
    uses: ./.github/workflows/build.yaml
    with:
      artifacts: true
  deploy:
    uses: ./.github/workflows/deploy-droplet.yaml
    needs: [build, test]
