name: Dev
on:
  workflow_dispatch:
  workflow_call:
defaults:
  run:
    shell: bash
env:
  TF_VAR_digitalocean_token: ${{ secrets.DIGITAL_OCEAN_APP_PLATFORM }}
  # TF_VAR_secops_key: ${{ secrets.SECOPS_KEY }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install SOPS
        run: |
          curl -LO https://github.com/getsops/sops/releases/download/v3.9.3/sops-v3.9.3.linux.amd64
          mv sops-v3.9.3.linux.amd64 /usr/local/bin/sops
          chmod +x /usr/local/bin/sops
      - name: Add PGP key
        run: |
          echo "${{ secrets.SOPS_KEY }}" | base64 -d > pgp.key
          gpg --import pgp.key
      - name: Decrypt app config
        run: |
          echo "TF_VAR_app_config=aGVsbG8gV29ybGQhCg==" >> "$GITHUB_ENV"
      - name: Echo app config
        run: |
          echo $TF_VAR_app_config
      
