name: Lint code
on:
  workflow_call:
defaults:
  run:
    shell: bash
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    container: golang:1.23.4-bullseye
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          skip-cache: true
